version: '3'

services:

  nginx:
    depends_on:
      - frontend
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'

  frontend:
    stdin_open: true
    build:
      context: ./frontend

