version: '3'

services:

  nginx:
    depends_on:
      - frontend
    # image: 'biotux7/nginx:latest'
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'

  frontend:
    # image: 'biotux7/frontend:latest'
    stdin_open: true
    build:
      context: ./frontend

